version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_service
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb_service
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  api:
    build: .
    container_name: fastify_api
    depends_on:
      - redis
      - mongodb
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongodb:27017/google_workspace_logs
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_ENV: production
    ports:
      - "3000:3000"
    restart: always

volumes:
  redis_data:
  mongo_data:
